[tool.poetry]
name = "index1"
version = "0.1.0"
description = ""
authors = ["Julien Bouquillon <julien.bouquillon@sg.social.gouv.fr>"]

[tool.poetry.dependencies]
python = "^3.11"
llama-index = "^0.8.40"
unstructured = {extras = ["md"], version = "^0.10.19"}
commonmark = "^0.9.1"
markdown-it-py = {extras = ["plugins"], version = "^3.0.0"}
python-frontmatter = "^1.0.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
