[browser]
gatherUsageStats = false

[logger]
level = debug

[client]
toolbarMode = developer


[theme]

# The preset Streamlit theme that your custom theme inherits from.
# One of "light" or "dark".
base = "light